version: '3.5'

networks:
  wordpress:

services:
  wordpress:
    container_name: wordpress
    depends_on:
      - db
    image: wordpress
    restart: always
    networks:
      - wordpress
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress:/var/www/html
      - ./docs:/var/www/docs

  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    networks:
      - wordpress
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./backup:/docker-entrypoint-initdb.d

  phpMyAdmin:
    container_name: phpMyAdmin
    image: phpmyadmin:5.2.0-apache
    depends_on:
      - db
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_USER: exampleuser
      PMA_PASSWORD: examplepass
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: '1'
    networks:
      - wordpress

volumes:
  wordpress:
