name: Generate xml sitemap

on:
  pull_request:
    branches: [ main ]

jobs:
  sitemap_job:
    runs-on: ubuntu-22.04
    name: Generate a sitemap

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://www.milouban.com
        path-to-root: docs

    - name: Output stats
      run: |
        echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"
        echo "sitemap:"
        cat ./docs/sitemap.xml

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: update sitemap.xml
        title: Update Sitemap
        body: Generate sitemap.xml
        base: main